### PR TITLE
WIP: GPU Operator: try to reproduce GPU Operator namespace error

### PR DESCRIPTION
**Pull request by mkowalski**
This is empty commit to trigger PSAP CI with the following commit of the gpu-operator - https://gitlab.com/mateusz.kowalski/gpu-operator/-/commit/b3543dac3aa9c7dd3e846e14170152d465e8320b

### CODE REVIEW

**Comment by kpouget** [comment]
```
2021-11-24T17:36:36.157Z	ERROR	controllers.ClusterPolicy	Failed to update ClusterPolicy status	{"error": "ClusterPolicy.nvidia.com \"gpu-cluster-policy\" is invalid: status.namespace: Required value"}
github.com/go-logr/zapr.(*zapLogger).Error
	/workspace/vendor/github.com/go-logr/zapr/zapr.go:132
github.com/NVIDIA/gpu-operator/controllers.updateCRState
	/workspace/controllers/clusterpolicy_controller.go:201
github.com/NVIDIA/gpu-operator/controllers.(*ClusterPolicyReconciler).Reconcile
	/workspace/controllers/clusterpolicy_controller.go:169
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:297
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:252
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/287/pull-ci-openshift-psap-ci-artifacts-master-gpu-operator-e2e/1463556535018852352/artifacts/gpu-operator-e2e/presubmit-master/artifacts/012__gpu-operator__must-gather/001__gpu_operator__capture_deployment_state/gpu_operator.log

**Comment by kpouget** [comment]
error is there in the nightly runs as well, but invisible as it doesn't crash the operator!
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-psap-ci-artifacts-release-4.9-gpu-operator-e2e-master/1463296498665000960/artifacts/gpu-operator-e2e-master/nightly/artifacts/012__gpu-operator__must-gather/001__gpu_operator__capture_deployment_state/gpu_operator.log

**Comment by mkowalski** [comment]
> https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/287/pull-ci-openshift-psap-ci-artifacts-master-gpu-operator-e2e/1463556535018852352/artifacts/gpu-operator-e2e/presubmit-master/artifacts/012__gpu-operator__must-gather/001__gpu_operator__capture_deployment_state/gpu_operator.log

Is this really running from my branch of the operator? I don’t see my custom marker in the log…

**Comment by kpouget** [comment]
> Is this really running from my branch of the operator? I don’t see my custom marker in the log…

no indeed, I found out yesterday evening that there's a bug in the deployment of the master branch image, it's always using an old one, I'm trying to fix it

**Comment by kpouget** [comment]
fix has been merged https://github.com/openshift-psap/ci-artifacts/pull/289

let's retry this:
/test gpu-operator-e2e

**Comment by kpouget** [comment]
flake

/test gpu-operator-e2e

**Comment by kpouget** [comment]
flake

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/287/pull-ci-openshift-psap-ci-artifacts-master-gpu-operator-e2e/1463966799748927488/artifacts/gpu-operator-e2e/presubmit-master/artifacts/000__gpu_operator__bundle_from_commit/_ansible.log
```
2021-11-25 21:29:59,929 p=87 u=psap-ci-runner n=ansible | ==> FAILED attempt #40/40
2021-11-25 21:29:59,929 p=87 u=psap-ci-runner n=ansible | <stdout> Error
2021-11-25 21:29:59,929 p=87 u=psap-ci-runner n=ansible | 
2021-11-25 21:30:32,248 p=87 u=psap-ci-runner n=ansible | ---
2021-11-25 21:30:32,248 p=87 u=psap-ci-runner n=ansible | 
2021-11-25 21:30:32,249 p=87 u=psap-ci-runner n=ansible | 
2021-11-25 21:30:32,249 p=87 u=psap-ci-runner n=ansible | ---
2021-11-25 21:30:32,249 p=87 u=psap-ci-runner n=ansible | roles/gpu_operator_bundle_from_commit/tasks/build_validator.yml:49
2021-11-25 21:30:32,249 p=87 u=psap-ci-runner n=ansible | TASK: gpu_operator_bundle_from_commit : Wait for the validator image to be built
2021-11-25 21:30:32,249 p=87 u=psap-ci-runner n=ansible | ----- FAILED ----
2021-11-25 21:30:32,249 p=87 u=psap-ci-runner n=ansible | 
2021-11-25 21:30:32,249 p=87 u=psap-ci-runner n=ansible | <command> oc get build.build.openshift.io/gpu-operator-validator-1 -ojsonpath={.status.phase} -n gpu-operator-ci
2021-11-25 21:30:32,249 p=87 u=psap-ci-runner n=ansible | 
2021-11-25 21:30:32,249 p=87 u=psap-ci-runner n=ansible | <stdout> Error
2021-11-25 21:30:32,249 p=87 u=psap-ci-runner n=ansible | ----- FAILED ----
2021-11-25 21:30:32,256 p=87 u=psap-ci-runner n=ansible | 
2021-11-25 21:30:32,256 p=87 u=psap-ci-runner n=ansible | Thursday 25 November 2021  21:30:32 +0000 (0:20:41.969)       0:28:41.573 ***** 
2021-11-25 21:30:34,791 p=87 u=psap-ci-runner n=ansible | ---
2021-11-25 21:30:34,791 p=87 u=psap-ci-runner n=ansible | 
2021-11-25 21:30:34,791 p=87 u=psap-ci-runner n=ansible | 
2021-11-25 21:30:34,791 p=87 u=psap-ci-runner n=ansible | ---
2021-11-25 21:30:34,791 p=87 u=psap-ci-runner n=ansible | roles/gpu_operator_bundle_from_commit/tasks/build_validator.yml:64
2021-11-25 21:30:34,792 p=87 u=psap-ci-runner n=ansible | TASK: gpu_operator_bundle_from_commit : Store the logs of validator image build (debug)
2021-11-25 21:30:34,792 p=87 u=psap-ci-runner n=ansible | msg: non-zero return code
2021-11-25 21:30:34,792 p=87 u=psap-ci-runner n=ansible | 
2021-11-25 21:30:34,792 p=87 u=psap-ci-runner n=ansible | <command> oc logs build.build.openshift.io/gpu-operator-validator-1 -n gpu-operator-ci > /logs/artifacts/000__gpu_operator__bundle_from_commit/validator-image-build.log
2021-11-25 21:30:34,792 p=87 u=psap-ci-runner n=ansible | 
2021-11-25 21:30:34,792 p=87 u=psap-ci-runner n=ansible | <stderr> Error from server (BadRequest): build gpu-operator-validator-1 is in an error state. No logs are available.
2021-11-25 21:30:34,794 p=87 u=psap-ci-runner n=ansible | PLAY RECAP *********************************************************************
```
the clusters seem to be be quite unstable lately, these flakes never happen usually, and I wonder why the logs are not available ......

**Comment by kpouget** [comment]
ok, I found the "flake" of the test:
```
    "test_operatorhub")
        if [[ -z "$*" ]]; then
            # Testing of v1.9.0-beta currently broken, use v1.8 instead
            test_operatorhub 1.8.2 v1.8
        else
            # Test the latest version available (using the PackageManifest default channel)
            test_operatorhub "$@"
            # test_operatorhub "$@"
            echo skip
        fi
...
    "cleanup_cluster")
        cleanup_cluster
        # cleanup_cluster
        exit 0
```
==> I commented out the *wrong `test_operatorhub` in the github editor, the one used in nighties and not in PRs,
so `test_operatorhub 1.8.2 v1.8` got executed, but `cleanup_cluster` wasn't.
`test_operatorhub` undeploys the entitlement at the end of its task, and `cleanup_cluster` should wait for it ...

**Comment by mkowalski** [comment]
In the current run I cannot reproduce the initially spotted issue. Every time `SetState()` is called, the correct namespace is present

```
2021-11-26T10:00:34.423Z	INFO	controllers.ClusterPolicy	CHOCOBOMB: This is a debug. Checking namespace value	{"operatorNamespace": "nvidia-gpu-operator"}
2021-11-26T10:00:34.423Z	INFO	controllers.ClusterPolicy	CHOCOBOMB: This is another inner debug. Checking passed namespace value	{"operatorNamespace": "nvidia-gpu-operator"}
```

Please note out of 3 custom markers, only 2 were present. Seems like we have never reached the following code
```
	if clusterPolicyCtrl.singleton != nil && clusterPolicyCtrl.singleton.ObjectMeta.Name != instance.ObjectMeta.Name {
		r.Log.Info("CHOCOBOMB: This is inner debug. Checking passed namespace value", "operatorNamespace", clusterPolicyCtrl.operatorNamespace)
		instance.SetStatus(gpuv1.Ignored, clusterPolicyCtrl.operatorNamespace)
		// do not change `clusterPolicyCtrl.operatorMetrics.reconciliationStatus` here,
		// spurious reconciliation
		return ctrl.Result{}, err
	}
```
however this is not the place where the initial issue was observed. We have seen it in `updateCRState()` and the marker from this function has been fired.

**Comment by kpouget** [comment]
ok, I got the explanation, sorry for the fuzz :#

there was an issue with the CI (solved by https://github.com/openshift-psap/ci-artifacts/pull/289), which made the CI use an old image for several days, ... but an up to date bundle definition (including the CRD),

so the image didn't set the `namespace` field, and CRD required it --> boom.

/close

**Pull request closed without merging**
