### PR TITLE
Wait for CSV and capture more info in case of failure

### PR DESCRIPTION
**Pull request by kpouget**

### CODE REVIEW

**Comment by kpouget** [comment]
(was closed by mistake)

/test gpu-operator-e2e

**Comment by dagrayvid** [comment]
I don't see any problems. Thanks @kpouget 

/lgtm

**Comment by kpouget** [comment]
\o/
/approve

@dagrayvid can be merged :)

**Comment by dagrayvid** [comment]
/lgtm

Thanks!

**Pull request merged**
