### PR TITLE
build/root/usr/local/bin/entitle.sh: update to use the new CI vault secrets

### PR DESCRIPTION
**Pull request by kpouget**
This PR updates the location of PSAP secret files, to deploy from the entitlement from PEM key, and deploy the CA PEM file required to access RHEL 8.4-beta repo mirror.

### CODE REVIEW

**Comment by kpouget** [comment]
retrying after deletion of the invalid PEM key

/test gpu-operator-e2e

**Comment by dagrayvid** [comment]
/lgtm

(assuming test passes)

**Comment by kpouget** [comment]
> Using '/var/run/psap-entitlement-secret/entitlement-key.pem' as PEM key

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/154/pull-ci-openshift-psap-ci-artifacts-master-gpu-operator-e2e/1392208989533507584/artifacts/gpu-operator-e2e/presubmit-operatorhub/build-log.txt

the entitlement was still deployed from the broken PEM key ...

the vault seems to be correct though, I removed the key yesterday. Maybe it's because of the propagation delay, retrying

CI vault

/test gpu-operator-e2e

**Comment by dagrayvid** [comment]
Sorry I missed that typo!

/lgtm

**Pull request merged**
