### PR TITLE
LTS Test Identifier work

### PR DESCRIPTION
**Pull request by kdvalin**

### CODE REVIEW

**Comment by kpouget** [comment]
@kdvalin , can you rebase and launch the light gating test?

**Comment by kdvalin** [comment]
[Test success,](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/803/pull-ci-openshift-psap-ci-artifacts-main-notebooks-light/1673736684241424384/artifacts/light/test/artifacts/001__notebook_scale_test_dsg/004__plots/lts_payload.json) identifier also propogates to the correct location

**Comment by kpouget** [comment]
cool,
can you just:
* move the OCP & RHODS version identifiers to the metadata,
* rebase
* launch the light test
and I'll merge it first thing tomorrow

**Comment by kpouget** [comment]
[test passed](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/803/pull-ci-openshift-psap-ci-artifacts-main-notebooks-light/1673841096314064896/artifacts/light/test/artifacts/report_index.html), but @kdvalin the notebook performance LTS payload doesn't have the test identifier field, can you please add it?

**Comment by kdvalin** [comment]
@kpouget [Test passed](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/803/pull-ci-openshift-psap-ci-artifacts-main-notebooks-light/1674088338027450368/artifacts/light/test/artifacts/002__rhods_notebook_performance/015__plots/lts_payload.json)

**Comment by kpouget** [comment]
thanks @kdvalin, I rebase and merge

**Pull request merged**
