### PR TITLE
Various CI updates

### PR DESCRIPTION
**Pull request by kpouget**
* 0e41ed2 - roles/nv_gpu/tasks/install_nv.yml: Save the GPU Operator PackageManifests: save YAML instead resource description

* 01533cf - roles/nv_gpu/tasks/main.yml: capture Operator Pod image in extra_logs_dir

### CODE REVIEW

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by kpouget** [comment]
/hold
I've not another commit to add

**Comment by kpouget** [comment]
@ArangoGutierrez new commits:

* 0106a31 - build/root/usr/local/bin/run: allow the local CI Pod to skip entitlement

This avoid this error when using the local CI toolbox command:

> $ toolbox/local-ci/deploy.sh 'run gpu-ci' https://github.com/openshift-psap/ci-artifacts.git master
> ...
> $ oc logs -f pod/ci-artifacts -n ci-artifacts
> FATAL: PSAP entitlement resources not found (/var/run/psap-entitlement-secret/01-cluster-wide-machineconfigs.yaml)

---

* f5105ef - roles/nv_gpu/tasks/install_nv.yml: force the label openshift.io/cluster-monitoring=true on the namespace
--> I don't know why [this bit](https://github.com/openshift-psap/ci-artifacts/blob/master/roles/nv_gpu/files/gpu/010_namespace.yml#L6) gets overwritten during the deployment ...

---

* d2d30cd - roles/nv_gpu/tasks/ci_checks.yml: wait 5*20s for DCGM to be picked up by Prom
--> I'm not sure how long it takes for Prom to pickup the service once it's deployed, we'll adjust that later

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
