### PR TITLE
Store ansible output as a json logfile

### PR DESCRIPTION
**Pull request by kpouget**
The purpose of this PR is to have another logfile using the JSON format, so that we can easily parse and display the result of the test steps in a website, by fetching the JSON logfile and plotting the relevant information in HTML.

### CODE REVIEW

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by kpouget** [comment]
@ArangoGutierrez I've updated the PR to generate a valid JSON file (instead of only the JSON list content)

/test gpu-operator-e2e

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
