### PR TITLE
testing: prow: SRO/GPU Operator: deploy NFD from source if not available in OperatorHub

### PR DESCRIPTION
**Pull request by kpouget**
NFD is [currently](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-psap-ci-artifacts-release-4.9-gpu-operator-e2e-master/1445539466482552832/artifacts/gpu-operator-e2e-master/nightly/artifacts/004__nfd_operator__deploy_from_operatorhub/_ansible.log) not available in its default OperatorHub location in 4.9 since 2021-09-30, deploy from sources when this happens:
```
2021-10-06 01:05:11,972 p=4517 u=psap-ci-runner n=ansible | roles/nfd_operator_deploy_from_operatorhub/tasks/main.yml:10
2021-10-06 01:05:11,972 p=4517 u=psap-ci-runner n=ansible | TASK: nfd_operator_deploy_from_operatorhub : Wait for the NFD to be available
2021-10-06 01:05:11,973 p=4517 u=psap-ci-runner n=ansible | ----- FAILED ----
2021-10-06 01:05:11,973 p=4517 u=psap-ci-runner n=ansible | msg: non-zero return code
2021-10-06 01:05:11,973 p=4517 u=psap-ci-runner n=ansible | 
2021-10-06 01:05:11,973 p=4517 u=psap-ci-runner n=ansible | <command> oc get packagemanifests/nfd -n openshift-marketplace
2021-10-06 01:05:11,973 p=4517 u=psap-ci-runner n=ansible | 
2021-10-06 01:05:11,973 p=4517 u=psap-ci-runner n=ansible | <stderr> Error from server (NotFound): packagemanifests.packages.operators.coreos.com "nfd" not found
2021-10-06 01:05:11,973 p=4517 u=psap-ci-runner n=ansible | ----- FAILED ----
```
image
image

### CODE REVIEW

**Comment by kpouget** [comment]
Hello @omertuc, could we merge this PR to fix the GPU Operator & SRO on 4.9? 
it replaces NFD from OperatorHub by NFD from master, if `packagemanifest/nfd` is not available

cc @dagrayvid @pacevedom @ArangoGutierrez

**Comment by omertuc** [comment]
/lgtm

But we should probably revert this once it's fixed, to simplify

**Pull request merged**
