### PR TITLE
 nfd_operator_deploy_from_operatorhub: use default channel from NFD CSV 

### PR DESCRIPTION
**Pull request by kpouget**
But it can be overriden from the command-line or with ansible args

### CODE REVIEW

**Comment by kpouget** [comment]
test `presubmit-operatorhub` passed [successfully](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/233/pull-ci-openshift-psap-ci-artifacts-master-gpu-operator-e2e/1423558723573387264/artifacts/gpu-operator-e2e/presubmit-operatorhub/artifacts/), this is what matters for this PR

/override gpu-operator-e2e

**Comment by kpouget** [comment]
/override  ci/prow/4.9-gpu-operator-e2e 
--> failure is unrelated, see https://github.com/openshift-psap/ci-artifacts/pull/236

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by kpouget** [comment]
thanks @*ArangoGutierrez*
/approve

**Pull request merged**
