### PR TITLE
load-aware: add support for LowRiskOverCommitment plugin

### PR DESCRIPTION
**Pull request by drewrip**

### CODE REVIEW

**Comment by kpouget** [comment]
looks good :)

**Comment by drewrip** [comment]
@kpouget Yeah can do, I might put that in a different PR though. It occurs to me that while the source for LowRiskOverCommitment was merged just a few weeks ago, the upstream trimaran scheduler image hasn't been updated in a couple months. So it definitely doesn't contain  the new plugin. `LowRiskOverCommitment` support is somewhat blocked by a new image being published.

**Comment by kpouget** [comment]
[test failed](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/855/pull-ci-openshift-psap-ci-artifacts-main-load-aware-light/1691015325115486208/artifacts/light/prepare/artifacts/005__load_aware__deploy_trimaran/trimaran_scheduler.log) because the plugin does not exist in the image we're using:
```
E0814 09:26:25.846610       1 run.go:74] "command failed" err="initializing profiles: creating profile for scheduler name trimaran-scheduler: ScorePlugin \"LowRiskOverCommitment\" does not exist"
```

**Comment by kpouget** [comment]
[test passed](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/855/pull-ci-openshift-psap-ci-artifacts-main-load-aware-light/1691021907274502144/artifacts/light/test/artifacts/003__trimaran_plots/report_00_report:_error_report.html) (without the `LowRiskOverCommitment` plugin). Merging.

**Pull request merged**
