### PR TITLE
More verbose failure when CR cannot be created

### PR DESCRIPTION
**Pull request by kpouget**

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
Relaunching all tests to see if this PR doesn't need a forced rebase, and if it still works after the last couple merges recently today

**Comment by kpouget** [comment]
wow, things went better than expected for 1.4:

> /usr/local/bin/run: line 121: exec: exit: not found

only `exec exit 0` failed ... because `exit` isn't a command -,-

pushed the fix, so this PR can go in from my POV

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
