### PR TITLE
testing: prow/gpu-operator.sh: properly capture the GPU Operator version

### PR DESCRIPTION
**Pull request by kpouget**
This got broken with the must-gather capture.

### CODE REVIEW

**Comment by kpouget** [comment]
`operator.version` properly captured:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/303/pull-ci-openshift-psap-ci-artifacts-master-gpu-operator-e2e/1470788467574181888/artifacts/gpu-operator-e2e/presubmit-operatorhub/artifacts/operator.version

/approve

@dagrayvid could we merge this one?

the second commit is to mute this error message when the GPU Operator operator isn't deployed:
```
Running the GPU Operator must-gather image ...
error: error executing jsonpath "{.items[0].spec.containers[0].image}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
	template was:
		{.items[0].spec.containers[0].image}
	object given to jsonpath engine was:
		map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}
```

**Comment by jmencak** [comment]
Thank you Kevin for the PR, the changes make sense to me and add some useful debugging information.
/lgtm

**Comment by kpouget** [comment]
thanks @jmencak :)

**Pull request merged**
