### PR TITLE
toolbox: add script to capture GPU Operator deployment state

### PR DESCRIPTION
**Pull request by kpouget**

### CODE REVIEW

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm
/hold

**Comment by kpouget** [comment]
/test gpu-operator-e2e

@ArangoGutierrez this version shouldn't have changed much since the one you acked, I only fixed `run` after `gpu-burn` was merged

**Review by ArangoGutierrez — COMMENTED** [review]
/lgtm

**Comment by kpouget** [comment]
rebased and fixed a rebase mistake:
```
-        exit 0toolbox/gpu-operator/capture_deployment_state.sh
+        exit 0
```

**Pull request merged**
