### PR TITLE
Various bug fixes and improvements

### PR DESCRIPTION
**Pull request by kpouget**
* db976a2 - roles/nv_gpu/tasks/install_nv.yml: search packagemanifests/gpu-operator-certified with a namespace

We see this failure in the nightly CI from time to time:

```
TASK: nv_gpu : Ensure that the GPU Operator PackageManifest exists
----- FAILED ----
msg: non-zero return code<command> oc get packagemanifests/gpu-operator-certified

<stderr> Error from server (NotFound): namespaces "ci-op-bz2h3t3n" not found
----- FAILED ----
```

but it cannot be easily reproduce by deleting projects or namespaces.
Hopefully, providing explicitly a namespace for the lookup will get
rid of the error.

---

* 794b833 - ansible.cfg: do not set log_path (was in $HOME)

---

* 86b4aa2 - build/root/usr/local/bin/run: set log_path inside artifacts dir

---

* 3f84fc6 - Do not set fact_caching_connection from 'ansible.cfg'

---

* 96024a4 - ansible.cfg: set retry_files_save_path in /tmp

---

* 86dc4c4 - ansible.cfg: don't disable deprecation_warnings

---

* 15591bd - Pass the inventory via ansible.cfg

---

* 8582d1d - roles/openshift_node/tasks/create_machine.yml: remove 'shell' tasks when possible

`shell` tasks as discouraged in ansible, and the aspect that is
problematic to us is that pipes will silently fail if not explicitly
marked with `-o pipefail`, eg:

```
<command> oc get machinesets -n openshift-machine-api -oname | grep
worker | head -1

<stderr> Unable to connect to the server: dial tcp:
lookup api.ci-op-wjm7mdpp-ed0e6.origin-ci-int-aws.dev.rhcloud.com on
172.30.0.10:53: read udp 10.129.5.98:38270->172.30.0.10:53: i/o
timeout

Wednesday 10 March 2021  23:46:22 +0000 (0:00:10.470) 0:00:12.437 *******
```

This task succeeded because `head` was happy, but `oc` wasn't.

As there is no way to set a global `set -o pipefail`, I prefer
rewriting `shell` tasks into commands, whenever possible (and step by
step, not all at once :)

---

* 08c84ab - build/root/usr/local/bin/run: allow receiving a PEM file from the CI infrastructure

The `run` script expects the cluster to be either:
- pre-entitled
- providing a PEM key located at `$ENTITLEMENT_PEM` or at
  `/var/run/psap-entitlement-secret/entitlement.pem`
- providing a resource file located at `$ENTITLEMENT_RESOURCES` or
  at
  `/var/run/psap-entitlement-secret/01-cluster-wide-machineconfigs.yaml`

In a followup commit, we will remove the hard-coded default paths and
rely only on the environment variables.

---

* d07450c - build/root/usr/local/bin/run: set ARTIFACT_DIR to '/tmp/ci-artifacts/date' if empty

And store in this directory:
- ARTIFACT_EXTRA_LOGS_DIR (from our ansible playbooks
- ANSIBLE_LOG_PATH (ansible logs)
- ANSIBLE_CACHE_PLUGIN_CONNECTION (ansible facts cache)

---

* 2effd86 - toolbox: gpu-operator/cleanup_resources.sh: new command

Removes the possibly stalled resources from a failed GPU Operator
deployment.

---

* 57cdad5 - toolbox/gpu-operator/_helm_common.sh: fix typo in log messages

---

* a68a7e7 - toolbox/gpu-operator/deploy_with_helm.sh: create GPU namespace only if it doesn't exist

---

* ecd5cf7 - toolbox: gpu-operator/list_version_from_operator_hub.sh: new script

---

* c532bbd - roles/nv_gpu/tasks/test_nfd_gpu.yml: better distinguish test vs wait failure message

---

* 2dd4c6f - toolbox/entitlement/test.sh: fix crash when --no-inspect is not passed

---

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
```bash
 PLAY RECAP *********************************************************************
localhost                  : ok=19   changed=14   unreachable=0    failed=2    skipped=3    rescued=0    ignored=1   
Monday 15 March 2021  14:52:13 +0000 (0:00:00.029)       0:00:09.544 ********** 
=============================================================================== 
check_deps : Capture OpenShift version (debug) -------------------------- 0.83s
check_deps : Fetch 'openshift_release' value and check dependencies ----- 0.69s
nv_gpu : capture Operator Pod image ------------------------------------- 0.62s
nv_gpu : get all machines (debug) --------------------------------------- 0.62s
nv_gpu : Ensure that NFD is running ------------------------------------- 0.60s
nv_gpu : get driver-container logs (debug) ------------------------------ 0.60s
nv_gpu : get all nodes (debug) ------------------------------------------ 0.60s
nv_gpu : capture GPU Pods states ---------------------------------------- 0.60s
nv_gpu : capture GPU Pod images ----------------------------------------- 0.59s
nv_gpu : get gpu-operator-resources DaemonSets (debug) ------------------ 0.59s
nv_gpu : CRD check - Ci mode -------------------------------------------- 0.57s
nv_gpu : capture GPU Nodes states --------------------------------------- 0.57s
nv_gpu : Ensure that NFD found nodes with GPU labels -------------------- 0.56s
nv_gpu : get gpu-operator-resources Pods (debug) ------------------------ 0.56s
nv_gpu : get GPU nodes (debug) ------------------------------------------ 0.53s
nv_gpu : include_tasks -------------------------------------------------- 0.05s
nv_gpu : include_tasks -------------------------------------------------- 0.05s
check_deps : Store openshift_release=4.7 -------------------------------- 0.04s
nv_gpu : Wait for NFD-labeled GPU nodes to appear ----------------------- 0.04s
nv_gpu : end of verbose failure (debug) --------------------------------- 0.04s 
```

/test gpu-operator-e2e

**Comment by kpouget** [comment]
The test failed because of this block missing the case when `nfd_wait_gpu_nodes != 'yes'`, so `has_gpu_nodes.sh` always returned `true` ...
```
  - name: Failing because no GPU node showed up
    fail:
      msg: Failed because no GPU node showed up
    when: nfd_wait_gpu_nodes == 'yes'  - name: Failing because no GPU node is available
    fail:
      msg: Failed because no GPU node is available
    when: nfd_wait_gpu_nodes == 'yes'
```

/test gpu-operator-e2e

**Comment by kpouget** [comment]
@ArangoGutierrez the test is passing, marking this PR as ready for review

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/86/pull-ci-openshift-
psap-ci-artifacts-master-gpu-operator-e2e/1371524640265998336/artifacts/gpu-operator-e2e/presubmit-operatorhub/build-log.txt

**Pull request merged**
