### PR TITLE
nfd_deploy: make sure we search only for the NFD ClusterServiceVersion

### PR DESCRIPTION
**Pull request by kpouget**
and fix indentation

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
gotta love indentation bugs

**Comment by kpouget** [comment]
hum, now I understand, the failure was introduced by this PR merged 3 days ago,
> https://github.com/openshift-psap/ci-artifacts/pull/122
but it only crashes 1/ when some operators are installed in all the namespaces 2/ before the NFD operator is installed

that's why the CI didn't catch it, the GPU Operator is installed in all the namespaces I think, but it happens after the NFD install

**Comment by kpouget** [comment]
/approve

@ArangoGutierrez or @dagrayvid , this one is ready for a fast ready for review & merging, it solves a bug in the current master branch

**Comment by kpouget** [comment]
I added two commits  to wait for the OperatorHub catalogs to be fully populated, instead of failing because the NFD/GPU Operator manifest are not available

/test gpu-operator-e2e

**Comment by dagrayvid** [comment]
This PR looks good, thanks. 
/lgtm

**Comment by kpouget** [comment]
thanks :)

**Pull request merged**
