### PR TITLE
Fix always-green testing

### PR DESCRIPTION
**Pull request by kpouget**

### CODE REVIEW

**Review by ArangoGutierrez — APPROVED** [review]
/joke

**Comment by kpouget** [comment]
I don't understand what's going on

/hold

```
export ARTIFACT_DIR=/tmp;export INSIDE_CI_IMAGE=y; ./build/root/usr/local/bin/run sd; echo return code: $?
===> Running PSAP CI Test suite <===
===> ./build/root/usr/local/bin/run sd <==
commit 81d7b9a8c2d100fdd74a8bdbf948d5cd4175128c (HEAD -> fix, private/fix)
Author: Kevin Pouget <kpouget@redhat.com>
Date:   Fri Jul 2 15:01:58 2021 +0200

    Fix always-green testing :(

commit 726e7155f9c57866737b4afbcd92ee38df58ce9e (origin/release-4.9, origin/release-4.8, origin/release-4.7, origin/release-4.6, origin/release-4.5, origin/master, origin/HEAD, master)
Author: Kevin Pouget <kpouget@redhat.com>
Date:   Fri Jul 2 09:03:29 2021 +0200

    CHANGELOG.rst: document s/subscription/subscriptions.operators.coreos.com fix

OpenShift version:
Client Version: 4.6.1
Server Version: 4.7.12
Kubernetes Version: v1.20.0+df9c838

Using KUBECONFIG=/home/kevin/openshift/clusters/kpouget-20210702/auth/kubeconfig

Test target: 'sd'; test action: ''

FATAL: Unknown target "sd"
Test of 'sd' failed.
return code: 1
```

**Comment by kpouget** [comment]
I know the problem:

```
handle_err() {
  set +e # <== I didn't want the error handling to change the test result :|
  echo handle_err
}

set -e
trap handle_err ERR

ech fail
echo bye
```

**Comment by kpouget** [comment]
/test gpu-operator-e2e

@omertuc link fixed, thanks

**Comment by kpouget** [comment]
```
2021-07-02 15:49:22,291 p=4623 u=psap-ci-runner n=ansible | ---
2021-07-02 15:49:22,291 p=4623 u=psap-ci-runner n=ansible | roles/gpu_operator_deploy_from_operatorhub/tasks/deploy_clusterpolicy.yml:33
2021-07-02 15:49:22,291 p=4623 u=psap-ci-runner n=ansible | TASK: gpu_operator_deploy_from_operatorhub : Wait for the GPU Operator ClusterPolicy CRD to appear
2021-07-02 15:49:22,291 p=4623 u=psap-ci-runner n=ansible | ----- FAILED ----
2021-07-02 15:49:22,291 p=4623 u=psap-ci-runner n=ansible | msg: non-zero return code
2021-07-02 15:49:22,291 p=4623 u=psap-ci-runner n=ansible | 
2021-07-02 15:49:22,292 p=4623 u=psap-ci-runner n=ansible | <command> oc get crd clusterpolicy.nvidia.com
2021-07-02 15:49:22,292 p=4623 u=psap-ci-runner n=ansible | 
2021-07-02 15:49:22,292 p=4623 u=psap-ci-runner n=ansible | <stderr> Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "clusterpolicy.nvidia.com" not found
2021-07-02 15:49:22,292 p=4623 u=psap-ci-runner n=ansible | ----- FAILED ----
2021-07-02 15:49:22,307 p=4623 u=psap-ci-runner n=ansible | 
2021-07-02 15:49:22,307 p=4623 u=psap-ci-runner n=ansible | Friday 02 July 2021  15:49:22 +0000 (0:05:13.737)       0:05:54.460 *********** 
2021-07-02 15:49:26,105 p=4623 u=psap-ci-runner n=ansible | ---
2021-07-02 15:49:26,105 p=4623 u=psap-ci-runner n=ansible | 
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/209/pull-ci-openshift-psap-ci-artifacts-master-gpu-operator-e2e/1410972859349602304/artifacts/gpu-operator-e2e/presubmit-operatorhub/artifacts/009__gpu-operator__deploy_from_operatorhub/_ansible.log

there is another problem with this part :(

I merge this PR as it can't make things worst than it is,

@omertuc @ArangoGutierrez please try to get it a shot on Monday
(@ArangoGutierrez  has approve rights)

**Pull request merged**
