### PR TITLE
RHODS: Add MatrixBenchmarking as a subproject

### PR DESCRIPTION
**Pull request by kpouget**
/cc @kpouget 

```
matbench-data-url: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/460/pull-ci-openshift-psap-ci-artifacts-master-ods-get-cluster/1551835589391683584/artifacts/get-cluster/test/artifacts/
```

### CODE REVIEW

**Comment by kpouget** [comment]
[Works](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/466/pull-ci-openshift-psap-ci-artifacts-master-ods-plot-jh-on-ocp/1552283716628254720/artifacts/plot-jh-on-ocp/test/artifacts/) \o/

Let's make sure that it works also with
/test ods-jh-on-single

**Review by fcami — APPROVED** [review]
/lgtm

**Comment by kpouget** [comment]
test succeeded, the plots have been [correctly generated](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/466/pull-ci-openshift-psap-ci-artifacts-master-ods-jh-on-single/1552296656915927040/artifacts/jh-on-single/test/artifacts/plotting/), good to merge

/hold cancel

**Pull request merged**
