### PR TITLE
Fix/oc

### PR DESCRIPTION
**Pull request by kpouget**
build/root/usr/local/bin/run: do not print git commit notes in the CI run info

    roles/nv_gpu/tasks/install.yml: remove trailing spaces

    roles/nv_gpu/tasks/install.yml: wait 5min for CRDs

    build/root/usr/local/bin/run: download latest 'oc' client if missing from PATH

### CODE REVIEW

**Comment by kpouget** [comment]
@ArangoGutierrez I force pushed these commits into `release-4.*` branches ... and things go better!

1. the `oc` CLI issue is worked around, so `4.7` and `4.8` (+ `master/4.6`) now run happily
2. however even with >13min delay, `4.4` and `4.5` failed, so the timing isn't the problem:
```
TASK [nv_gpu : Failed when creating the test clusterpolicy CR for the GPU Operator] ***
task path: /opt/ci-artifacts/src/playbooks/roles/nv_gpu/tasks/install.yml:34
Monday 25 January 2021  00:02:38 +0000 (0:14:05.971)       0:19:00.739 ******** 
fatal: [localhost]: FAILED! => {
    "changed": false,
    "msg": {
        "attempts": 40,
        "changed": true,
        "cmd": [
            "oc",
            "apply",
            "-f",
            "roles/nv_gpu/files/041_customresources.yaml"
        ],
        "delta": "0:00:00.922756",
        "end": "2021-01-25 00:02:38.876660",
        "failed": true,
        "msg": "non-zero return code",
        "rc": 1,
        "start": "2021-01-25 00:02:37.953904",
        "stderr": "error: unable to recognize \"roles/nv_gpu/files/041_customresources.yaml\": no matches for kind \"NodeFeatureDiscovery\" in version \"nfd.openshift.io/v1alpha1\"",
        "stderr_lines": [
            "error: unable to recognize \"roles/nv_gpu/files/041_customresources.yaml\": no matches for kind \"NodeFeatureDiscovery\" in version \"nfd.openshift.io/v1alpha1\""
        ],
        "stdout": "",
        "stdout_lines": []
    }
}
```

**Comment by ArangoGutierrez** [comment]
> @ArangoGutierrez I force pushed these commits into `release-4.*` branches ... and things go better!
> 
>     1. the `oc` CLI issue is worked around, so `4.7` and `4.8` (+ `master/4.6`) now run happily
> 
>     2. however even with >13min delay, `4.4` and `4.5` failed, so the timing isn't the problem:
> 
> 
> ```
> TASK [nv_gpu : Failed when creating the test clusterpolicy CR for the GPU Operator] ***
> task path: /opt/ci-artifacts/src/playbooks/roles/nv_gpu/tasks/install.yml:34
> Monday 25 January 2021  00:02:38 +0000 (0:14:05.971)       0:19:00.739 ******** 
> fatal: [localhost]: FAILED! => {
>     "changed": false,
>     "msg": {
>         "attempts": 40,
>         "changed": true,
>         "cmd": [
>             "oc",
>             "apply",
>             "-f",
>             "roles/nv_gpu/files/041_customresources.yaml"
>         ],
>         "delta": "0:00:00.922756",
>         "end": "2021-01-25 00:02:38.876660",
>         "failed": true,
>         "msg": "non-zero return code",
>         "rc": 1,
>         "start": "2021-01-25 00:02:37.953904",
>         "stderr": "error: unable to recognize \"roles/nv_gpu/files/041_customresources.yaml\": no matches for kind \"NodeFeatureDiscovery\" in version \"nfd.openshift.io/v1alpha1\"",
>         "stderr_lines": [
>             "error: unable to recognize \"roles/nv_gpu/files/041_customresources.yaml\": no matches for kind \"NodeFeatureDiscovery\" in version \"nfd.openshift.io/v1alpha1\""
>         ],
>         "stdout": "",
>         "stdout_lines": []
>     }
> }
> ```

Interesting, maybe we need to change the CSV channel for `release-4.5` 
and remember 4.4 is deprecated now, so wont fix.

**Comment by kpouget** [comment]
I removed the last commit https://github.com/openshift-psap/ci-artifacts/commit/313e7d00ae53557d2bf188966eec84d6f1cf1dda (wait 13min for CRDs) as the issue wasn't there

**Comment by kpouget** [comment]
added a commit to capture Pod&Node info when all the test succeed

**Comment by kpouget** [comment]
@ArangoGutierrez if you have time to review this PR today, I'd like to get it merged to run it overnight

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
