### PR TITLE
refactoring: refactor 'entitlement' role

### PR DESCRIPTION
**Pull request by kpouget**
Refactoring of the big roles into multiple smaller roles.
Current role: entitlement

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
uh..... @kpouget why ?

**Comment by ArangoGutierrez** [comment]
https://github.com/openshift/release/pull/16944 is merged, yaml lint should be good now

**Comment by kpouget** [comment]
>  FileNotFoundError: [Errno 2] No such file or directory: 'configs/.yamllint.conf' 

it will take a bit of time to the bot to pick it up

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
