### PR TITLE
{nfd,gpu}_operator_deploy_from_operatorhub: better wait for packagemanifest to be available

### PR DESCRIPTION
**Pull request by kpouget**
Cluster Pools (cf this https://github.com/openshift/release/pull/20601) fail because of this error:
```
2021-07-27 09:18:54,314 p=2875 u=psap-ci-runner n=ansible | roles/nfd_operator_deploy_from_operatorhub/tasks/main.yml:10
2021-07-27 09:18:54,314 p=2875 u=psap-ci-runner n=ansible | TASK: nfd_operator_deploy_from_operatorhub : Ensure that the NFD Operator PackageManifest exists
2021-07-27 09:18:54,314 p=2875 u=psap-ci-runner n=ansible | msg: non-zero return code
2021-07-27 09:18:54,314 p=2875 u=psap-ci-runner n=ansible | 
2021-07-27 09:18:54,315 p=2875 u=psap-ci-runner n=ansible | <command> oc get packagemanifests/nfd -n openshift-marketplace
2021-07-27 09:18:54,315 p=2875 u=psap-ci-runner n=ansible | 
2021-07-27 09:18:54,315 p=2875 u=psap-ci-runner n=ansible | <stderr> error: the server doesn't have a resource type "packagemanifests"
2021-07-27 09:18:54,324 p=2875 u=psap-ci-runner n=ansible | 
2021-07-27 09:18:54,324 p=2875 u=psap-ci-runner n=ansible | Tuesday 27 July 2021  09:18:54 +0000 (0:00:00.531)       0:00:01.602 ********** 
2021-07-27 09:18:54,959 p=2875 u=psap-ci-runner n=ansible | ---
```
(the resource `type` is not available). That's not expected and not something we hit before. 
This PR makes sure we wait for the package manifest to be available.

---

The previous code was "waiting" (as opposed to checking) for the catalogue operator to be Ready or the package to be available (assuming that when the operator is ready, everything else shouldn't move anymore)

now, the code simply waits for the package to be available, oblivious to other implementation considerations

### CODE REVIEW

**Comment by omertuc** [comment]
Can you elaborate on how deleting that previous code helps ensure that? What was wrong with what the previous code is doing?

**Comment by kpouget** [comment]
the previous code was "waiting" (as opposed to checking) for the catalogue operator to be `Ready` or the package to be available (assuming that when the operator is ready, everything else shouldn't move anymore)

now, the code simply waits for the package to be available, oblivious to other implementation considerations

I think I already removed this construct for the GPU Operator as I saw it didn't do well what I intended (the operator can be `Ready` and package can be missing or available "randomly")

**Comment by omertuc** [comment]
> the previous code was "waiting" (as opposed to checking) for the catalogue operator to be `Ready` or the package to be available (assuming that when the operator is ready, everything else shouldn't move anymore)
> 
> now, the code simply waits for the package to be available, oblivious to other implementation considerations
> 
> I think I already removed this construct for the GPU Operator as I saw it didn't do well what I intended (the operator can be `Ready` and package can be missing or available "randomly")

I see. That makes sense.

Looks like the rehearsals are failing on a similar thing with the GPU operator now, so maybe you didn't remove this construct for the GPU operator after all

**Comment by kpouget** [comment]
> Looks like the rehearsals are failing on a similar thing with the GPU operator now, so maybe you didn't remove this construct for the GPU operator after all

indeed :(

I've updated the PR, I'll wait for https://github.com/openshift/release/pull/20601 to be merged before retrying the test with a cluster from the pool

**Comment by omertuc** [comment]
> /test gpu-operator-e2e

This should be pooled now, right?

**Comment by kpouget** [comment]
> > /test gpu-operator-e2e
> 
> This should be pooled now, right?

yes!
```
INFO[2021-07-27T11:55:00Z] Waiting for the claimed cluster to be ready. 
INFO[2021-07-27T11:59:15Z] The claimed cluster is ready after 4m14s.    
```

**Comment by kpouget** [comment]
@omertuc test passed, I think we can merge this PR

**Comment by kpouget** [comment]
thanks Omer :)

**Pull request merged**
