### PR TITLE
roles/nv_gpu/files/031_operator_sub.yaml: make NFD channel dependent of OCP version

### PR DESCRIPTION
**Pull request by kpouget**

### CODE REVIEW

**Comment by kpouget** [comment]
the patch that ran last night was wrong, the template `{{ nfd_channel }}` was applied to the GPU-Operator subscription, so of course it didn't work ...

PR updated.

**Comment by kpouget** [comment]
@ArangoGutierrez this PR is still failing, could you have a look?

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/15328/rehearse-15328-pull-ci-openshift-psap-ci-artifacts-release-4.5-gpu-operator-e2e-presubmit/1354732656637513728
```
 commit 218f76ad568dac4e47bead915e887ef6b6fcad31
Author: Kevin Pouget <kpouget@redhat.com>
Date:   Tue Jan 26 14:27:53 2021 +0100
    roles/nv_gpu/files/031_operator_sub.yaml: make NFD channel dependent of OCP version 
```

```
 fatal: [localhost]: FAILED! => {
    "attempts": 20,
    "changed": true,
    "cmd": [
        "oc",
        "apply",
        "-f",
        "roles/nv_gpu/files/041_customresources.yaml"
    ],
    "delta": "0:00:00.684847",
    "end": "2021-01-28 11:00:25.377787",
    "invocation": {
        "module_args": {
            "_raw_params": "oc apply -f \"roles/nv_gpu/files/041_customresources.yaml\"",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2021-01-28 11:00:24.692940",
    "stderr": "error: unable to recognize \"roles/nv_gpu/files/041_customresources.yaml\": no matches for kind \"NodeFeatureDiscovery\" in version \"nfd.openshift.io/v1alpha1\"",
    "stderr_lines": [
        "error: unable to recognize \"roles/nv_gpu/files/041_customresources.yaml\": no matches for kind \"NodeFeatureDiscovery\" in version \"nfd.openshift.io/v1alpha1\""
    ],
    "stdout": "",
    "stdout_lines": []
} 
```

**Comment by kpouget** [comment]
This subscription is created with `nfd_channel=4.5`, is that correct?
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nfd
  namespace: openshift-nfd
spec:
  channel: "{{ nfd_channel }}"
  installPlanApproval: Automatic
  name: nfd
  source: redhat-operators
  sourceNamespace: openshift-marketplace
```
https://github.com/openshift-psap/ci-artifacts/pull/43/files#diff-8ea437fbd6075b14a57fe130e19b54fe524b64c7cc98389259196b611cff5b51L7-R7
```
 changed: [localhost] => {
    "changed": true,
    "cmd": "sed 's|{{ nfd_channel }}|4.5|' \"roles/nv_gpu/files/031_operator_sub.yaml\" | oc apply -f \"roles/nv_gpu/files/032_operator_sub.yaml\"",
    "delta": "0:00:00.531339",
    "end": "2021-01-28 10:55:08.862023",
    "invocation": {
        "module_args": {
            "_raw_params": "sed 's|{{ nfd_channel }}|4.5|' \"roles/nv_gpu/files/031_operator_sub.yaml\" | oc apply -f \"roles/nv_gpu/files/032_operator_sub.yaml\"",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": false
        }
    },
    "rc": 0,
    "start": "2021-01-28 10:55:08.330684",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "subscription.operators.coreos.com/gpu-operator-certified created",
    "stdout_lines": [
        "subscription.operators.coreos.com/gpu-operator-certified created"
    ]
} 
```

**Review by ArangoGutierrez — APPROVED** [review]
This is something to watch for everytime we get a new release 
/lgtm

**Pull request merged**
