### PR TITLE
nfd_operator_deploy_from_operatorhub: fix broken path to files

### PR DESCRIPTION
**Pull request by kpouget**

### CODE REVIEW

**Comment by jmencak** [comment]
/lgtm
Thank you for the fix, Kevin.

**Comment by kpouget** [comment]
thanks @jmencak, I'm working on a precheck test to ensure this does happen anymore!

/test gpu-operator-e2e

**Comment by kpouget** [comment]
```
 <command> oc get -oyaml CatalogSource/redhat-operators -n openshift-marketplace -ojsonpath={.status.connectionState.lastObservedState}{"\n"}
<stdout> TRANSIENT_FAILURE 
```
```
 ----- FAILED ----
msg: non-zero return code
<command> oc get packagemanifests/nfd -n openshift-marketplace
<stderr> Error from server (NotFound): packagemanifests.packages.operators.coreos.com "nfd" not found
----- FAILED ---- 
```
:'(

**Comment by kpouget** [comment]
> /lgtm
> Thank you for the fix, Kevin.

@jmencak if you're OK with it I will manually merge this PR, upgrade tests run today around noon, I'd like to try to get them running with this fix merged

**Comment by jmencak** [comment]
@kpouget fine by me to merge, this can only fix things...

**Pull request merged**
