### PR TITLE
WIP: download coco dataset from CI

### PR DESCRIPTION
**Pull request by kpouget**

### CODE REVIEW

**Comment by kpouget** [comment]
/test gpu-operator-commit

@pamann @omertuc FYI

... but downloading the [dataset](https://mirror-dataset.apps.ci-mirror.psap.aws.rhperfscale.org/coco/train2017.zip)  fails in my cluster, I'm not sure why ...

```
sh-4.4# time curl  -E $CERT_FILE $DATASET_URL_BASE/$DATASET_FILENAME | md5sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- -  0     0    0     0    0     0      0      0 --:--:-- -  0 18.0G    0 40.3M    0     0  34.9M      0  0:08:48    0 18.0G    0 42.5M    0     0  19.6M      0  0:15:38    0 18.0G    0 74.5M    0     0  23.6M      0  0:12:59    0 18.0G    0  116M    0     0  28.0M      0  0:10:58    1 18.0G    1  184M    0     0  35.8M      0  0:08:34    1 18.0G    1  210M    0     0  34.2M      0  0:08:58    1 18.0G    1  277M    0     0  38.7M      0  0:07:55    1 18.0G    1  346M    0     0  42.4M      0  0:07:14    2 18.0G    2  409M    0     0  44.7M      0  0:06:52    2 18.0G    2  473M    0     0  46.6M      0  0:06:35    2 18.0G    2  542M    0     0  48.6M      0  0:06:19    3 18.0G    3  611M    0     0  50.3M      0  0:06:06    3 18.0G    3  679M    0     0  51.6M      0  0:05:56    3 18.0G    3  723M    0     0  49.7M      0  0:06:10    3 18.0G    3  723M    0     0  49.7M      0  0:06:11  0:00:14  0:05:57 56.7M
curl: (18) transfer closed with 18578364572 bytes remaining to read
85b0f0a2da2084b9e277194dba236596  -
```

(it works in my machine)

**Comment by kpouget** [comment]
```
+ curl -E /etc/mirror-secret/mirror.pem https://mirror-dataset.apps.ci-mirror.psap.aws.rhperfscale.org/coco/train2017.zip
...
cced6f7f71b7629ddf16f17bbcfab6b2  -

real	18m18.835s
user	0m55.481s
sys	0m46.765s
+ oc delete pod/download-mirror -n default
pod "download-mirror" deleted
+ echo 'final state: Succeeded'
final state: Succeeded
+ exit 0
Test of 'gpu-operator test_commit' succeeded.
```
it seems that it worked as expected :)

@pamann you can take inspiration of that (quick and dirty :#) to create the secret, mount into the Pod and download the dataset

@omertuc could you try to confirm the md5sum, just to be sure?

I wonder why the download failed when I tried in my cluster, I hope it will be stable in the CI ...

**Comment by omertuc** [comment]
> @omertuc could you try to confirm the md5sum, just to be sure?

image

**Pull request closed without merging**
