### PR TITLE
check_deps: capture 'oc whoami' value

### PR DESCRIPTION
**Pull request by kpouget**

### CODE REVIEW

**Comment by kpouget** [comment]
working as [expected](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/304/pull-ci-openshift-psap-ci-artifacts-master-gpu-operator-e2e/1471144169043922944/artifacts/gpu-operator-e2e/presubmit-operatorhub/artifacts/000__cluster__capture_environment/_ansible.log):
```
2021-12-15 15:49:05,395 p=93 u=psap-ci-runner n=ansible | roles/check_deps/tasks/main.yml:57
2021-12-15 15:49:05,395 p=93 u=psap-ci-runner n=ansible | TASK: check_deps : Get the cluster username (debug)
2021-12-15 15:49:05,395 p=93 u=psap-ci-runner n=ansible | 
2021-12-15 15:49:05,395 p=93 u=psap-ci-runner n=ansible | <command> oc whoami
2021-12-15 15:49:05,395 p=93 u=psap-ci-runner n=ansible | 
2021-12-15 15:49:05,395 p=93 u=psap-ci-runner n=ansible | <stdout> system:admin
2021-12-15 15:49:05,402 p=93 u=psap-ci-runner n=ansible | 
2021-12-15 15:49:05,402 p=93 u=psap-ci-runner n=ansible | Wednesday 15 December 2021  15:49:05 +0000 (0:00:00.459)       0:00:03.185 **** 
2021-12-15 15:49:05,921 p=93 u=psap-ci-runner n=ansible | ---
```

capturing this bit of information only for trouble shooting, in case the user isn't `system:admin` / the expected one ...

**Comment by jmencak** [comment]
Thank you for the PR, Kevin!
/lgtm

**Comment by kpouget** [comment]
thanks @jmencak 

/approve

**Pull request merged**
