### PR TITLE
Run CI on local cluster

### PR DESCRIPTION
**Pull request by kpouget**
This PR allows running a given commit of the `ci-artifact` repository on a local OpenShift cluster:

Example:
```
./build/root/usr/local/bin/run ci-builder https://github.com/openshift-psap/ci-artifacts.git master
```

I mark this PR as draft because the command to run on the CI pod is currently hardcoded in `roles/build_ci_image/files/execution_pod.yaml`:

```
spec:
  containers:
  - name: ci-artifacts
    command:
    - /bin/sh
    - -c
    - bash -x run gpu-commit-ci https://gitlab.com/kpouget_psap/gpu-operator devel
```

I would like to be able to pass `run gpu-commit-ci https://gitlab.com/kpouget_psap/gpu-operator devel` in the `run` command-line above, as `ANSIBLE_OPTS` or directly on the command-line.

### CODE REVIEW

**Comment by kpouget** [comment]
I'll update the PR tomorrow to turn this feature into the toolbox script, cf some commits in this PR: https://github.com/openshift-psap/ci-artifacts/pull/45

**Review by kpouget — COMMENTED** [review]
need to make all files extension consistent --> `.yml`

**Comment by kpouget** [comment]
UPDATE: goes on top of https://github.com/openshift-psap/ci-artifacts/pull/52

I improved the code and integrated it in the toolbox.
Last missing step is to control the command that will be executed in the CI pod from the command line.

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by ArangoGutierrez** [comment]
Again OOKilled, , I know it feels random, but we should consider bumping it up a bit 
/test images

**Comment by kpouget** [comment]
> Again OOKilled, , I know it feels random, but we should consider bumping it up a bit
do we have a control over this ?

**Pull request merged**
