### PR TITLE
Improve logs readability

### PR DESCRIPTION
**Pull request by kpouget**
Ansible logs are hard to read with stderr/stdout lines duplicated and everything mangled in JSON.
This patch adds a Python output callback to print more readable information while keeping the gist of it.

### CODE REVIEW

**Comment by kpouget** [comment]
/test gpu-operator-e2e

@ArangoGutierrez :

the previous test failed because of the missing `callback_plugins` directory; 
I added this commit https://github.com/openshift-psap/ci-artifacts/pull/50/commits/9d03a4c8be0c574e0d3592a252f3ed3bdb084289 to include all the repository in the container image

**Comment by kpouget** [comment]
need to handle better `for/item` types:
```
/home/kevin/openshift/ci-artifacts/roles/nv_gpu/tasks/uninstall_nv.yml:11
changed: [localhost] => (item=clusterserviceversion.operators.coreos.com/gpu-operator-certified.v1.5.2) => {"ansible_loop_var": "item", "changed": true, "cmd": "oc delete clusterserviceversion.operators.coreos.com/gpu-operator-certified.v1.5.2 -n openshift-operators", "delta": "0:00:02.725913", "end": "2021-02-11 09:42:45.185144", "item": "clusterserviceversion.operators.coreos.com/gpu-operator-certified.v1.5.2", "rc": 0, "start": "2021-02-11 09:42:42.459231", "stderr": "", "stderr_lines": [], "stdout": "clusterserviceversion.operators.coreos.com \"gpu-operator-certified.v1.5.2\" deleted", "stdout_lines": ["clusterserviceversion.operators.coreos.com \"gpu-operator-certified.v1.5.2\" deleted"]}
TASK: nv_gpu : Delete the ClusterServiceVersion of the GPU Operator
msg: All items completed
changed: True
  - results:	[{'cmd': 'oc delete clusterserviceversion.operators.coreos.com/gpu-operator-certified.v1.5.2 -n openshift-operators', 'stdout': 'clusterserviceversion.operators.coreos.com "gpu-operator-certified.v1.5.2" deleted', 'stderr': '', 'rc': 0, 'start': '2021-02-11 09:42:42.459231', 'end': '2021-02-11 09:42:45.185144', 'delta': '0:00:02.725913', 'changed': True, 'invocation': {'module_args': {'_raw_params': 'oc delete clusterserviceversion.operators.coreos.com/gpu-operator-certified.v1.5.2 -n openshift-operators', '_uses_shell': True, 'warn': True, 'stdin_add_newline': True, 'strip_empty_ends': True, 'argv': None, 'chdir': None, 'executable': None, 'creates': None, 'removes': None, 'stdin': None}}, 'stdout_lines': ['clusterserviceversion.operators.coreos.com "gpu-operator-certified.v1.5.2" deleted'], 'stderr_lines': [], '_ansible_no_log': False, 'failed': False, 'item': 'clusterserviceversion.operators.coreos.com/gpu-operator-certified.v1.5.2', 'ansible_loop_var': 'item', '_ansible_item_label': 'clusterserviceversion.operators.coreos.com/gpu-operator-certified.v1.5.2'}]
```

**Comment by kpouget** [comment]
@ArangoGutierrez I think this one is good for merging, if the test returns green

/test gpu-operator-e2e

**Comment by ArangoGutierrez** [comment]
OutOfMemoryKilled... we need to bump the resources we are asking to the CI

**Comment by kpouget** [comment]
@ArangoGutierrez this one will be able to go in when the test completes :)

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/50/pull-ci-openshift-psap-ci-artifacts-master-gpu-operator-e2e/1360249214294036480/artifacts/gpu-operator-e2e/presubmit-operatorhub/build-log.txt

```
Friday 12 February 2021  16:10:17 +0000 (0:00:00.661)       0:00:04.158 ******* 
TASK: openshift_node : Get worker machineset template
changed: True

<command> bash -c oc get machineset 'ci-op-2l3yl0bv-0e4b4-5hz42-worker-us-west-2a' --kubeconfig '/tmp/tmp.YRJdEX5ZAI' -n openshift-machine-api -o json
```

```
/opt/ci-artifacts/src/playbooks/roles/openshift_node/tasks/scaleup_checks.yml:36
Friday 12 February 2021  16:10:18 +0000 (0:00:00.720)       0:00:05.601 ******* 
TASK: openshift_node : Generate GPU machine set file
changed: True

<command> roles/openshift_node/files/aws_machineset_json.sh gpu_machineset_aws_template.json g4dn.xlarge
```

these two commands should be rewritten to avoid spamming the logs ;-)

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
