### PR TITLE
Update Ci-artifacts

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
This patch updates the ci-artifacs for the GPU testing

Updates NFD to 4.6 CSV
Updates GPU operator to 1.4 CSV
Update default OCP version to 4.6

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Review by kpouget — CHANGES_REQUESTED** [review]
thanks for the PR @ArangoGutierrez, 

could you split these files in 2, one side for the NFD, one side for the NV-GO?

> roles/nv_gpu/files/04_customresources.yaml 
> roles/nv_gpu/files/01_namespace.yaml 

I guess that could help reusing them more easily if the files for both operators are well separated

**Review by kpouget — COMMENTED** [review]
and actually, I'm surprised to see some filenames changed, but no update in the ansible scripts?

**Comment by ArangoGutierrez** [comment]
@kpouget Ready for round 2

**Comment by ArangoGutierrez** [comment]
@kpouget PTAL

**Review by kpouget — APPROVED** [review]

**Pull request merged**
