### PR TITLE
Improve and refactor build/root/usr/local/bin/run to rely on the toolbox

### PR DESCRIPTION
**Pull request by kpouget**
* 8d9c558 - build/Dockerfile: delete ${HOME}/ansible.cfg from the image

This patch should remove this warning from the CI logs:

> [WARNING]: Ansible is being run in a world writable directory (/opt/ci-
artifacts/src), ignoring it as an ansible.cfg source. For more information see
https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-
world-writable-dir

---

* 8976a7c - build/root/usr/local/bin/run: mute tar commands and show git HEAD~ in CI image

Prevent `tar` from listing the files files it `untar`, and show
`HEAD~` commit info (for presubmit, HEAD is the merge commit...)

---

* 81b0d06 - build/root/usr/local/bin/run: export ANSIBLE_OPTS as default options for toolbox scripts

Pass `ANSIBLE_OPTS` as default ansible args to the `toolbox` scripts

---

* 6aa4829 - build/root/usr/local/bin/run: refactor to rely on the toolbox scripts

Transform calls to `ansible-playbook` into call to `toolbox` scripts

---

* f29648e - roles/check_deps/tasks/main.yml: fix undefined variable name when KUBECONFIG does not exist

`check_deps` error message was crashing when `KUBECONFIG` was not
defined ...

---

* 3010d1e - roles/nv_gpu: deploy the last version of the GPU Operator from OperatorHub

Finish the automation of the OperatorHub deployment; the actual
significant modification is that the ClusterPolicy object is taken
from the `PackageManifest / alm-example` instead of being stored in a
file

---

* b2e9b7d - roles/build_ci_image: remove files/helm_deploy_operator.sh (local_ci_helm_install)

This script wasn't used.

---

### CODE REVIEW

**Comment by kpouget** [comment]
/test gpu-operator-14

rebased on top of https://github.com/openshift-psap/ci-artifacts/pull/58

**Comment by kpouget** [comment]
/test gpu-operator-e2e

the `gpu-operator-e2e` test failed because of the entitlement already existing in the cleanup and master branch tests (only the first OperatorHub test passed)

```
===> Apply entitlement manifests from /var/run/psap-entitlement-secret/01-cluster-wide-machineconfigs.yaml<==
Error from server (AlreadyExists): error when creating "/var/run/psap-entitlement-secret/01-cluster-wide-machineconfigs.yaml": machineconfigs.machineconfiguration.openshift.io "50-rhsm-conf" already exists
Error from server (AlreadyExists): error when creating "/var/run/psap-entitlement-secret/01-cluster-wide-machineconfigs.yaml": machineconfigs.machineconfiguration.openshift.io "50-entitlement-pem" already exists
Error from server (AlreadyExists): error when creating "/var/run/psap-entitlement-secret/01-cluster-wide-machineconfigs.yaml": machineconfigs.machineconfiguration.openshift.io "50-entitlement-key-pem" already exists
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-02-17T01:21:59Z"}
error: failed to execute wrapped command: exit status 1
```
The `gpu-operator-e2e` test failed because of the entitlement already
existing in the `cleanup and `master branch` tests (only the first
`OperatorHub` test passed).

Patch 7daabfcc6310267 makes sure that we don't try to create the entitlement
twice.

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
