### PR TITLE
RHODS: Remove the dependency on Github for notebooks + various updates

### PR DESCRIPTION
**Pull request by kpouget**
This PR refactors the fetching of the notebook file inside the notebook pod (sic): until now, we were cloning the notebook from Github, but it is a bad practice to use their servers as part of the scale testing. Besides, a significant part of the `git clone` were failing, likely because of GH throttling.

This PR introduces an HTTP server (nginx) role, which is used to host our playbook file in the driver cluster, and instructs the test suite to fetch it from there.

The PR also moves the location of the calls reset the Prometheus databases, to move it closer to the actual beginning of the test.

---

* `cluster_deploy_minio_s3_server: use the namespace variable instead of hardcoded value`

This was a silent mistake, as the namespace variable currently has the
value as the hardcoded string that was in the code. But it would make
the role fail if ever we decide to launch `minio` in another
namespace.

---

* `cluster_deploy_nginx_server: new role`

This role takes a directory in parameter (in addition to the
namespace), which contains the files to server over HTTP.

The role generates a file named `hostname` in its artifact directory,
containing the address at which the HTTP server is listening.

No HTTPS is possible at the moment, this is much more complex to set
up.

---

* `rhods_test_jupyterlab: add notebook_url parameter`

This commit allows the Ansible role to receive a `notebook_url`
parameter. The role fetches the notebook to validate the URL, then
passes the value to the test Job with the `NOTEBOOK_URL` environment
variable.

---

* `rhods_test_jupyterlab: refactor and update the robot to curl the notebook`

This commit refactors the Robot test to improve its readability. By
choice, I preferred keeping multiple test-cases, instead of a single
test-case + keywords (functions) being called from it.

This improves the readability of the container logs, as well as the
parsing and plotting of the timestamp and duration of the different
steps (test cases in practice) of the test, eg:

```
==============================================================================
Test-Jupyterlab-Run-Notebook
==============================================================================
Open the Browser                                                      | PASS |
------------------------------------------------------------------------------
Go to RHODS Dashboard                                                 | PASS |
------------------------------------------------------------------------------
Go to JupyterHub                                                      | PASS |
------------------------------------------------------------------------------
Spawn a Notebook                                                      | PASS |
------------------------------------------------------------------------------
Load the Notebook                                                     | PASS |
------------------------------------------------------------------------------
Run the Notebook                                                      | PASS |
------------------------------------------------------------------------------
Test-Jupyterlab-Run-Notebook                                          | PASS |
6 tests, 6 passed, 0 failed
==============================================================================
```

---

* `rhods_test_jupyterlab: capture the notebook pods definition`

This wasn't possible until recently, as we were terminating the Pods
from inside the Robot. Now that they stay alive after the end of the
Job execution, we can capture the Pod definitions for post-mortem
processing.

---

* `testing: ods: jh-at-scale: deploy nginx and fetch the notebook from there`

This commit deploys our nginx notebook server, and instructs
`rhods_test_jupyterlab` to fetch it from there.

---

* `testing: ods: jh-at-scale: remove calls to reset_prometheus_db`

Resetting Prometheus DB at this location is too far away from the
actual start of the scale test, leading to too many useless metrics
points at the beginning of the test.

---

* `rhods_test_jupyterlab: add calls to reset_prometheus_db`

Moved this call from _before_ the beginning of the
`rhods_test_jupyterlab` role to right before the creation of the test
job, so that the delay between the reset and the actual test creation
is minimal. In particular, the pre-fetching of the image of the Pod
takes a significant time.

---

* `toolbox: cluster: fix typos in documentation`

Minor changes in `reset_prometheus_db` and `dump_prometheus_db`.

---

/cc @fcami

### CODE REVIEW

**Comment by fcami** [comment]
Thanks @kpouget for the detailed commits!!!

/lgtm

**Comment by kpouget** [comment]
cluster creation [flake](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/422/pull-ci-openshift-psap-ci-artifacts-master-ods-jh-on-ocp/1545478844385857536/artifacts/jh-on-ocp/create-clusters/artifacts/ocp_sutest_install.log) :(
```

level=error msg=Cluster initialization failed because one or more operators are not functioning properly.
level=error msg=The cluster should be accessible for troubleshooting as detailed in the documentation linked below,
level=error msg=https://docs.openshift.com/container-platform/latest/support/troubleshooting/troubleshooting-installations.html
level=error msg=The 'wait-for install-complete' subcommand can then be used to continue the installation
level=fatal msg=failed to initialize the cluster: Working towards 4.10.15: 668 of 771 done (86% complete)
make[1]: Leaving directory '/opt/ci-artifacts/src/subprojects/deploy-cluster'
```

/test ods-jh-on-ocp

**Comment by kpouget** [comment]
prow/image failure is a flake,
test passed at [15/15,](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/422/pull-ci-openshift-psap-ci-artifacts-master-ods-jh-on-ocp/1546034499190525952/artifacts/jh-on-ocp/test/artifacts/006__driver_rhods__test_jupyterlab/success_count)
@fcami approved before the weekend,
merging.

**Pull request merged**
