### PR TITLE
refactoring: remove unused roles

### PR DESCRIPTION
**Pull request by kpouget**

### CODE REVIEW

**Comment by kpouget** [comment]
> @kpouget: The following test **failed**, say `/retest` to rerun all failed tests:
> Test name 	Commit 	Details 	Rerun command
> ci/prow/yamllint 	[2eaf1c7](https://github.com/openshift-psap/ci-artifacts/commit/2eaf1c7a35d1f3435dbb66e1de4291312ced5f0e) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/98/pull-ci-openshift-psap-ci-artifacts-yamllint/1372558153605976064) 	`/test yamllint`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openshift-psap&repo=ci-artifacts&pr=98). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:kpouget).

this was expected as the PR moves the YAML configuration file to make it more visisble configs/.yamllint.conf ⟶   config/yamllint.conf

I hesitated to put it in `.github` as it's a presubmit check, but on the other hand it's not related to GH, so I let it in a general purpose `config` directory

**Review by ArangoGutierrez — APPROVED** [review]
Out with the old, bring in the new! 
/lgtm

**Pull request merged**
