### PR TITLE
RHODS: Use a single configuration file

### PR DESCRIPTION
**Pull request by kpouget**
/var rhods.catalog.image=quay.io/modh/qe-catalog-source
/var rhods.catalog.tag=v1180-8

### CODE REVIEW

**Comment by kpouget** [comment]
[previous test passed \o/](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/545/pull-ci-openshift-psap-ci-artifacts-main-ods-notebooks/1587787617691242496/artifacts/notebooks/)

**Review by fcami — APPROVED** [review]
/lgtm 
Will have a longer look later if there is still time.

**Pull request merged**
