### PR TITLE
Remove RHEL 8.4-beta flags

### PR DESCRIPTION
**Pull request by kpouget**

### CODE REVIEW

**Comment by omertuc** [comment]
image
Best kind of PR

/lgtm

/test gpu-operator-e2e

**Comment by kpouget** [comment]
\test 4.8-gpu-operator-e2e

**Comment by kpouget** [comment]
> image
> Best kind of PR
> 
> /lgtm
> 
> /test gpu-operator-e2e

thanks @omertuc 
I'll try to test it on 4.8 before merging, once https://github.com/openshift/release/pull/18635 has been taken into account by the bot

**Comment by kpouget** [comment]
The `uninstall` is part (between `operatorhub` and `master` tests)  is getting unreliable since a few days, that's really weird
```
[ 1855.109901] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[ 1855.167348] device veth7d516149 entered promiscuous mode
[ 1855.383297] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[ 1855.391079] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[ 1855.418045] device veth4b1f3857 entered promiscuous mode
[ 1855.459500] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[ 1855.474931] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[ 1855.524184] device veth02de996c entered promiscuous mode
[ 1890.939165] nvidia-modeset: Unloading
[ 1891.088577] nvidia-uvm: Unloaded the UVM driver.
[ 1891.097173] nvidia-nvlink: Unregistered the Nvlink Core, major device number 235
[ 1892.947139] nvidia-nvlink: Nvlink Core is being initialized, major device number 235
[ 1892.995514] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  460.32.03  Sun Dec 27 19:00:34 UTC 2020
[ 1893.070703] nvidia-uvm: Loaded the UVM driver, major device number 511.
[ 1893.109154] nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  460.32.03  Sun Dec 27 18:51:11 UTC 2020
[ 2042.473931] nvidia-uvm: Unloaded the UVM driver.
[ 2042.491598] nvidia-modeset: Unloading
[ 2042.509524] nvidia-nvlink: Unregistered the Nvlink Core, major device number 235
[ 2043.116132] nvidia-nvlink: Nvlink Core is being initialized, major device number 234
[ 2043.162036] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  460.73.01  Thu Apr  1 21:40:36 UTC 2021
[ 2043.196795] nvidia-uvm: Loaded the UVM driver, major device number 510.
[ 2043.203374] nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  460.73.01  Thu Apr  1 21:32:31 UTC 2021
[ 2043.206730] nvidia-modeset: Unloading
[ 2043.353075] nvidia-uvm: Unloaded the UVM driver.
[ 2043.365951] nvidia-nvlink: Unregistered the Nvlink Core, major device number 234
Installing 'NVIDIA Accelerated Graphics Driver for Linux-x86_64' (460.73.01):
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/165/pull-ci-openshift-psap-ci-artifacts-master-gpu-operator-e2e/1395388798744924160/artifacts/gpu-operator-e2e/gather-extra/artifacts/pods/gpu-operator-resources_nvidia-driver-daemonset-86jg2_nvidia-driver-ctr.log
this shows that the driver of `1.6.2` (v460.32.03) wasn't properly removed when testing `1.7.0` ...

**Comment by kpouget** [comment]
`OperatorHub` test succeeded, so the entitlement part is solved ...!
```
INFO[2021-05-20T17:55:12Z] Running step gpu-operator-e2e-presubmit-operatorhub. 
INFO[2021-05-20T18:22:12Z] Step gpu-operator-e2e-presubmit-operatorhub succeeded after 27m0s. 
INFO[2021-05-20T18:22:12Z] Running step gpu-operator-e2e-presubmit-operatorhub-cleanup. 
INFO[2021-05-20T18:23:12Z] Step gpu-operator-e2e-presubmit-operatorhub-cleanup succeeded after 1m0s. 
INFO[2021-05-20T18:23:12Z] Running step gpu-operator-e2e-presubmit-master. 
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/165/pull-ci-openshift-psap-ci-artifacts-master-4.8-gpu-operator-e2e/1395409398846722048

/approve

**Comment by kpouget** [comment]
merging, `4.8-gpu-operator-e2e` passed, it's what mattered for this test

**Comment by kpouget** [comment]
great @dagrayvid 

feel free to create a PR for https://github.com/openshift-psap/ci-dashboard/, 
hopefully you should just have to duplicate&adapt https://github.com/openshift-psap/ci-dashboard/blob/master/examples/gpu-operator.yml (+ GitHub actions)

**Pull request merged**
