### PR TITLE
apply entitlement manifests when running on CI image

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by kpouget** [comment]
hey, can you protect the `oc create` with `[[ "${INSIDE_CI_IMAGE:-}" == "y" ]]` so that it happens only in the CI ?
(and add a `p` to apply ;-)

**Comment by kpouget** [comment]
with the fix above, good to merge :)

**Comment by ArangoGutierrez** [comment]
> with the fix above, good to merge :)
 PTAL

**Comment by ArangoGutierrez** [comment]
Ready for review @kpouget

**Comment by dagrayvid** [comment]
With the changes suggested by @kpouget, /lgtm

**Pull request merged**
