### PR TITLE
gpu_operator_deploy_from_operatorhub: Capture the state of the CatalogSource/certified-operators

### PR DESCRIPTION
**Pull request by kpouget**
Fix ansible escaping of `"`

### CODE REVIEW

**Comment by kpouget** [comment]
```
roles/gpu_operator_deploy_from_operatorhub/tasks/main.yml:1
TASK: gpu_operator_deploy_from_operatorhub : Capture the state of the CatalogSource/certified-operators (debug)

<command> oc get -oyaml CatalogSource/certified-operators -n openshift-marketplace -ojsonpath={.status.connectionState.lastObservedState}{"\n"}

<stdout> READY
```
good to merge @ArangoGutierrez 

\hold cancel
\approve

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
