### PR TITLE
Fix a couple of toolbox documentation typos

### PR DESCRIPTION
**Pull request by omertuc**

### CODE REVIEW

**Comment by kpouget** [comment]
thanks @omertuc 
no need to test on OpenShift as it's doc only,
/lgtm
/approve

**Comment by jmencak** [comment]
Just for completenes, Kevin beat me to this. :)
/lgtm

**Comment by kpouget** [comment]
> Just for completenes, Kevin beat me to this. :)
> /lgtm

lol ;-) this PR is a follow-up of https://github.com/openshift-psap/ci-artifacts/pull/214#issuecomment-887313806 where I suggested to fix these nits in a dedicated PR rather than forcing a full re-check !

**Comment by kpouget** [comment]
> /test gpu-operator-e2e

@omertuc, docs are covered by Github actions :)

image

**Comment by omertuc** [comment]
> > /test gpu-operator-e2e
> 
> @omertuc, docs are covered by Github actions :)
> 
> image

But it `gpu-operator-e2e` is `Required`

**Comment by kpouget** [comment]
in practise, `Required` means "must not be marked as failing",
so if the test is never (manually) started, it never failed ^^^

**Pull request merged**
