### PR TITLE
roles/nv_gpu_install_from_commit/files/helm_deploy_operator.sh: do not fix 1.4.0 deployment

### PR DESCRIPTION
**Pull request by kpouget**

### CODE REVIEW

**Comment by kpouget** [comment]
/test gpu-operator-14

Test failed because of this error in the Driver container, I don't understand why:

```
Installing elfutils...
+ dnf install -q -y elfutils-libelf.x86_64 elfutils-libelf-devel.x86_64
Error: Unable to find a match: elfutils-libelf-devel.x86_64
```

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/57/pull-ci-openshift-psap-ci-artifacts-master-gpu-operator-14/1361667237257154560/artifacts/gpu-operator-14/gather-extra/artifacts/pods/gpu-operator-resources_nvidia-driver-daemonset-ps4gl_nvidia-driver-ctr.log

**Comment by ArangoGutierrez** [comment]
> /test gpu-operator-14
> 
> Test failed because of this error in the Driver container, I don't understand why:
> 
> ```
> Installing elfutils...
> + dnf install -q -y elfutils-libelf.x86_64 elfutils-libelf-devel.x86_64
> Error: Unable to find a match: elfutils-libelf-devel.x86_64
> ```
> 
> https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/57/pull-ci-openshift-psap-ci-artifacts-master-gpu-operator-14/1361667237257154560/artifacts/gpu-operator-14/gather-extra/artifacts/pods/gpu-operator-resources_nvidia-driver-daemonset-ps4gl_nvidia-driver-ctr.log

that means the entitlements didn't worked most of the times

**Comment by kpouget** [comment]
This is an expected failure: 

[Pods](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/57/pull-ci-openshift-psap-ci-artifacts-master-gpu-operator-14/1362072489932361728/artifacts/gpu-operator-14/gpu-helm-ci/artifacts/gpu-helm-ci/extra_logs/debug_gpu_pods_list):
```
NAME                                       READY   STATUS                 RESTARTS   AGE   IP             NODE                           NOMINATED NODE   READINESS GATES
nvidia-container-toolkit-daemonset-pnj4z   1/1     Running                0          14m   10.130.2.4     ip-10-0-138-177.ec2.internal   <none>           <none>
nvidia-device-plugin-daemonset-jlqlr       0/1     CreateContainerError   0          12m   10.130.2.6     ip-10-0-138-177.ec2.internal   <none>           <none>
nvidia-driver-daemonset-mv8nl              1/1     Running                0          15m   10.0.138.177   ip-10-0-138-177.ec2.internal   <none>           <none>
nvidia-driver-validation                   0/1     Completed              0          14m   10.130.2.5     ip-10-0-138-177.ec2.internal   <none>           <none>
```

[Images](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/57/pull-ci-openshift-psap-ci-artifacts-master-gpu-operator-14/1362072489932361728/artifacts/gpu-operator-14/gpu-helm-ci/artifacts/gpu-helm-ci/extra_logs/gpu_pods_image):
```
nvidia-container-toolkit-daemonset-pnj4z:	nvcr.io/nvidia/k8s/container-toolkit:1.4.0-ubi8, 
nvidia-device-plugin-daemonset-jlqlr:	nvcr.io/nvidia/k8s-device-plugin:v0.7.1-ubi8, 
nvidia-driver-daemonset-mv8nl:	nvcr.io/nvidia/driver:450.80.02-rhcos4.6, 
nvidia-driver-validation:	nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2, 
```

[Reason](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/57/pull-ci-openshift-psap-ci-artifacts-master-gpu-operator-14/1362072489932361728/artifacts/gpu-operator-14/gather-extra/artifacts/pods.json):
```
                        "state": {
                            "waiting": {
                                "message": "container create failed: time=\"2021-02-17T17:20:29Z\" level=error msg=\"container_linux.go:366: starting container process caused: exec: \\\"--mig-strategy=none\\\": executable file not found in $PATH\"\n",
                                "reason": "CreateContainerError"
                            }
```

**Pull request closed without merging**
