### PR TITLE
roles/openshift_node: make more generic (remove GPU-specific aspect)

### PR DESCRIPTION
**Pull request by kpouget**
> toolbox/scaleup_cluster.sh [new machine type]

This command scales up the cluster using the optional machine type
passed in parameter (the default value is controlled via
`machine_instance_type` in `group_var/all.yml`).

By "scaling up" here, we mean: ensure that a Machine with the given
machine type is available in cluster.

The name of the generated `MachineSet` is also updated to include the
machine type name, so that the cluster can easily be scaled-up with
different machine types.

### CODE REVIEW

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by kpouget** [comment]
/hold
need to see why the check failed

**Comment by kpouget** [comment]
/test gpu-operator-e2e

hum, there was still a call to the old script name ... Fixed.
```
-        toolbox/scaleup_gpu_node.sh
+        toolbox/scaleup_cluster.sh
         toolbox/nfd/deploy_from_operatorhub.sh
         toolbox/gpu-operator/deploy_from_commit.sh "${CI_IMAGE_GPU_COMMIT_CI_REPO}" \
```

**Comment by kpouget** [comment]
@ArangoGutierrez test passed :)

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
