### PR TITLE
Group config files together

### PR DESCRIPTION
**Pull request by kpouget**
* a58d1ac - config: make yamllint.conf visible

---

* d057c85 - Move ansible.cfg to config/ansible.cfg and update accordingly

---

### CODE REVIEW

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by kpouget** [comment]
Force merged, the `yamllint` configuration was moved so the test could never pass.
Now we should be able to merge https://github.com/openshift/release/pull/16944

**Pull request merged**
