### PR TITLE
NFD add test_branch function

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
Run ansible-lint on the playbooks and roles / build (pull_request) 
LOL I didn't modified any role 🙃

**Comment by fcami** [comment]
> render_group



> ```
> + ansible-lint -v --force-color -c config/ansible-lint.yml playbooks roles
> INFO     Added ANSIBLE_ROLES_PATH=~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:roles
> Traceback (most recent call last):
>   File "/usr/local/bin/ansible-lint", line 8, in <module>
>     sys.exit(_run_cli_entrypoint())
>   File "/usr/local/lib/python3.9/site-packages/ansiblelint/__main__.py", line 276, in _run_cli_entrypoint
>     sys.exit(main(sys.argv))
>   File "/usr/local/lib/python3.9/site-packages/ansiblelint/__main__.py", line 192, in main
>     from ansiblelint.generate_docs import rules_as_rich, rules_as_rst
>   File "/usr/local/lib/python3.9/site-packages/ansiblelint/generate_docs.py", line 6, in <module>
>     from rich.console import render_group
> ImportError: cannot import name 'render_group' from 'rich.console' (/usr/local/lib/python3.9/site-packages/rich/console.py)
> ```
> 
> first time I see this, my other PR don't fail on it ...

Because it was removed 2 days ago: https://github.com/Textualize/rich/commit/ad9debf2eb5a04cea709d35a7bc03f316bf0431c

**Comment by kpouget** [comment]
cool, thanks for checking @fcami, so the issue should solve itself soon :)

**Comment by ArangoGutierrez** [comment]
PR doesn't affects how GPU's get tested 
/override ci/prow/gpu-operator-e2e

**Pull request merged**
