### PR TITLE
load-aware: control preset for manual test

### PR DESCRIPTION
**Pull request by drewrip**

### CODE REVIEW

**Comment by kpouget** [comment]
visualization [failed](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/863/pull-ci-openshift-psap-ci-artifacts-main-load-aware-e2e/1684489603047755776/artifacts/e2e/test/artifacts/001__trimaran_plots/_matbench_visualize.log)
```
  File "/opt/ci-artifacts/src/subprojects/matrix-benchmarking/matrix_benchmarking/workloads/load-aware/plotting/pod_times.py", line 115, in do_plot
    q1, med, q3 = stats.quantiles(df.Duration)
  File "/usr/lib64/python3.9/statistics.py", line 640, in quantiles
    raise StatisticsError('must have at least two data points')
statistics.StatisticsError: must have at least two data points
```
because of [this](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/863/pull-ci-openshift-psap-ci-artifacts-main-load-aware-e2e/1684489603047755776/artifacts/e2e/test/artifacts/000__load_aware_scale_test_trimaran_scheduler/001__load_aware__scale_test/scale_test_pods.status):
```
NAME                    READY   STATUS      RESTARTS   AGE
coreutils-make-pod-n0   0/1     Completed   0          2m3s
```

I don't think you really expected to have only one Pod, but please update the visualization code to avoid calling `stats.quantiles(df.Duration)` and alike when there's 0 or 1 row in the data frame
(dealing with incomplete data is haard, in the visualization you cannot predict what will be there and what won't, but step by step you can make it more resilient 🙃)

when you have updated the visualization, you can launch this to confirm that it overcomes the failure of the last test:
``
test load-aware-plot https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/863/pull-ci-openshift-psap-ci-artifacts-main-load-aware-e2e/1684489603047755776/artifacts/e2e/test/artifacts/000__load_aware_scale_test_trimaran_scheduler/
```

**Comment by drewrip** [comment]
@kpouget I didn't think this would be a real failure! This test created the cluster I was using for manual testing and I assumed I mucked up the test before it finished.

I'll take care of this and the issue on the `LowRiskOverCommitment` plugin PR, in one joint PR tomorrow

**Pull request closed without merging**
